name: myPlugin
version: '${project.version}'
main: fr.utoka.myplugin.MyPlugin
api-version: 1.19
authors: [Utoka]
description: MC
commands:
  G-getMoney:
    description: Get money
    permission: G-getMoney.use
#  G-giveMoney:
#    description: Give money
#    permission: G-giveMoney.use
  test:
    description: Envois message test
    permission: test.use
  alert:
    description: Envois un broadcast
    permission: alert.use
  aide:
    description: Aide pour les commandes
    permission: aide.use