name: myPlugin
version: '${project.version}'
main: fr.utoka.myplugin.MyPlugin
api-version: 1.19
authors: [Utoka]
description: MC
commands:
  g-ping:
    description: Envois pong
  g-getMoney:
    description: Afficher son argent
  g-removeMoney:
    description: Enlever de l'argent à quelqu'un ou son argent
    permission: getMoney.use
  g-giveMoney:
    description: Ajouter de l'argent à quelqu'un ou à soi-même argent
    permission: giveMoney.use
  g-setMoney:
    description: Remettre l'argent à quelqu'un ou son propre argent à ce qu'on souhaite
    permission: setMoney.use
  g-alert:
    description: Envois un broadcast
    permission: alert.use
  g-help:
    description: Aide pour les commandes
    permission: g-aide.use
  g-givesword:
    description: Give des swords meta
    permission: g-give.use
  g-fly:
    description: Permet de fly
    permission: g-fly.use