name: myPlugin
version: '${project.version}'
main: fr.utoka.myplugin.MyPlugin
api-version: 1.19
authors: [Utoka]
description: MC
commands:
  g-ping:
    description: Envois pong
    permission: test.use
  g-alert:
    description: Envois un broadcast
    permission: alert.use
  g-help:
    description: Aide pour les commandes
    permission: g-aide.use
  g-givesword:
    description: Give des swords meta
    permission: g-give.use