name: myPlugin
version: '1.0-SNAPSHOT'
main: fr.utoka.myplugin.MyPlugin
api-version: 1.19
authors: [Utoka]
description: MC
commands:
  test:
    description: Envois message test
    permission: test.use
  alert:
    description: Envois un broadcast
    permission: alert.use
  aide:
    description: Aide pour les commandes
    permission: aide.use